Build test env

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -11,36 +11,31 @@ jobs:
   homework-checker-infra:
     runs-on: ubuntu-22.04
     steps:
-      - run: echo "Checking file q1_create_employee_table.sql"
-      - run: echo "Done. Cool!"
-      - run: echo "Checking file q2_insert_employee_table.sql"
-      - run: echo "Done. Cool!"
-      - run: echo "Checking file q3_create_visit_log_table.sql"
-      - run: echo "Done. Cool!"
-      - run: echo "Checking file q4_insert_visit_log_table.sql"
-      - run: echo "Done. Cool!"
-      - run: echo "Checking file q5_employee_female.sql"
-      - run: echo "Done. Cool!"
-      - run: echo "Checking file q6_employee_male.sql"
-      - run: echo "Done. Cool!"
-      - run: echo "Checking file q7_visit_log_cnt.sql"
-      - run: echo "Done. Cool!"
-      - run: echo "Checking file q8_visit_log_group_by_purpose_cnt.sql"
-      - run: echo "Done. Cool!"
-      - run: echo "Checking file q9_find_visit_employee.sql"
-      - run: echo "Done. Cool!"
-      - run: echo "Checking file q10_update_peach_position.sql"
-      - run: echo "Done. Cool!"
-      - run: echo "Checking file q10_update_peach_position.sql"
-      - run: echo "Done. But fail, I've got unexpected result from the query file"
-    # container: python:3.9.15
-    # services:
-    #   postgres:
-    #     image: postgres:14.5
-    #     ports:
-    #       - 5432:5432
-    #     environment:
-    #       POSTGRES_PASSWORD: pg-admin
-    #       POSTGRES_USER: pg-admin
-    #       POSTGRES_DB: pytest
-    #     restart: always
+      - name: Check out repository
+        uses: actions/checkout@v3
+      - name: List directory for debugging
+        run: ls -a ${{ github.workspace }}
+      - name: Build the stack for homework
+        run: docker-compose up -d
+      - name: Install Poetry
+        uses: snok/install-poetry@v1
+      - name: Set up python
+        id: setup-python
+        uses: actions/setup-python@v4
+        with:
+          python-version: '3.11'
+      - name: Load cached venv
+        id: cached-poetry-dependencies
+        uses: actions/cache@v3
+        with:
+          path: .venv
+          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
+      - name: Install dependencies
+        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
+        run: poetry install --no-interaction --no-root
+      - name: List directory for debugging
+        run: ls -a ${{ github.workspace }}
+      - name: Your score is...
+        run: bash run-test.sh
+      - name: Stop Docker Compose services || echo "Failed to graceful shutdown, ignored"
+        run: docker-compose down
